### ISSUE TITLE
the order isssue v_ordered(set()) in function of weighted_graph.py

### ISSUE THREAD

**Issue by saber131421** [jperdomo23/openmht#10]
v_ordered = set()
        degrees = list(enumerate(self.vertex_degrees(g)))
        while degrees:
            min_index, min_value = min(degrees, key=operator.itemgetter(1))
            v_ordered.add(min_index)
            degrees.remove((min_index, min_value))
Hello here I see you made a sort for degrees,but you put the min_index into the set. We can't control the order in the set.
Does this destroy the previous sorting?

**Comment by jonperdomo** [comment]
I updated the set to a list, thank you for catching that.

**Comment by jonperdomo** [comment]
Please use the following command to pull these updates:
`pip install openmht --upgrade `
