### ISSUE TITLE
plot_tracks update

### ISSUE THREAD

**Issue by crchinn** [jperdomo23/openmht#15]
[](url)
[plot_tracks.zip](https://github.com/jonperdomo/openmht/files/12807786/plot_tracks.zip)

I found a bug in the plot_tracks routine.  I attached a zip of the corrected version with some additions. 

The last track was not plotted.

**Comment by jonperdomo** [comment]
Okay seems like an improvement, thank you!
![Figure_1](https://github.com/jonperdomo/openmht/assets/14855676/4bd2b2b3-c86a-4a2d-a233-7bb7fb31cfb7)

**Comment by crchinn** [comment]
There was an error in the old version where the last track was not
appended.
