### ISSUE TITLE
missing ParameterFile.txt for SampleData

### ISSUE THREAD

**Issue by bsdis** [jperdomo23/openmht#16]
It is unfortunate that there is no ParameterFile.txt for the sampledata. For new users, looking to quickly try out the library it needs to be easy to run the sample or they might quickly leave again and use another library instead. Can you please provide a ParameterFile.txt file for the sampledata so that one might try out the application.
Thank you

**Comment by jonperdomo** [comment]
The default parameter file [params.txt](https://github.com/jonperdomo/openmht/blob/main/params.txt) included in the repository can be used.

**Comment by jonperdomo** [comment]
I updated the README for clarity as well
