### ISSUE TITLE
To GPS

### ISSUE THREAD

**Issue by CalenDario13** [jperdomo23/openmht#17]
Is it possible to adapt the csv or the algorithm to GPS data? and what about "v" parameter with these kind of data?

I want to pass to the algorithm gps positions insted of pixels. The idea is to ave a map and detect points on it.

**Comment by jonperdomo** [comment]
Yes the V parameter (measurement space) is only used to estimate the likelihood under the null hypothesis, so it does not necessarily have to be image area:
<img width="113" alt="image" src="https://github.com/jonperdomo/openmht/assets/14855676/a99e6043-ee43-4304-8d97-cd0c082f5623">

**Comment by CalenDario13** [comment]
and what about the coordinates, can I use them as U and V values?

**Comment by jonperdomo** [comment]
Yes, any set of 2D coordinates work.

**Comment by CalenDario13** [comment]
Great, sorry for the additional question: the V parameter must be set in such a way that the coordinates would be inside an imaginary rectangle drawn aroun thaem?

**Comment by jonperdomo** [comment]
Yes, you can define the measurement space as the bounding box around your points (xmin, ymin, xmax, ymax).
