### ISSUE TITLE
Value for probability of detection P_D

### ISSUE THREAD

**Issue by SiddharthDey** [jperdomo23/openmht#20]
In the repository, the probability of detection P_D is taken as 1/V. The default value for V is set as 307200; hence, the value for the missed detection score becomes close to 0 (-3.255213631532517e-06) as 1/V is very small. This happens in line 20 of [kalman_filter.py](https://github.com/jonperdomo/openmht/blob/main/openmht/kalman_filter.py):

```
self.__missed_detection_score = np.log(1. - (1. / self.__image_area))
```

However, the paper mentions that they have taken P_D as 0.9, without much detail as to why they used this value:
![Screenshot from 2023-12-19 17-46-26](https://github.com/jonperdomo/openmht/assets/52491801/0a056e39-d403-4ba5-91c2-3c8f8244eb93)

However, the probability of detection should be high. If we take P_D as 1/V, the value of P_D becomes very small as compared to 0.9. Should we assume P_D and 1/V to have the same values? If not, how do we define the value of P_D?

**Comment by jonperdomo** [comment]
I use 1/V as an estimate of the probability of detection (P_D), and that is how the uniform likelihood under the null hypothesis for a track is defined, but this might be incorrect:

<img width="141" alt="image" src="https://github.com/jonperdomo/openmht/assets/14855676/88cbf097-635e-4d87-a8cd-3372067bcd9d">

From the paper the probability of a false alarm (P_FA) is negligible, but probability of detection (P_D) should be large:
<img width="406" alt="image" src="https://github.com/jonperdomo/openmht/assets/14855676/74c52b98-b52d-4e27-898c-fcbfc73c668b">

I can test with a larger value such as 0.9 in their performance evaluation.
Thank you for identifying this issue!

**Comment by SiddharthDey** [comment]
#

> I use 1/V as an estimate of the probability of detection (P_D), and that is how the uniform likelihood under the null hypothesis for a track is defined, but this might be incorrect:
> 
> <img alt="image" width="141" src="https://private-user-images.githubusercontent.com/14855676/291947920-88cbf097-635e-4d87-a8cd-3372067bcd9d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMxMTUyODcsIm5iZiI6MTcwMzExNDk4NywicGF0aCI6Ii8xNDg1NTY3Ni8yOTE5NDc5MjAtODhjYmYwOTctNjM1ZS00ZDg3LWE4Y2QtMzM3MjA2N2JjZDlkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIwVDIzMjk0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI1YTNkZTM4ZTg2MWZhMGRmYWI0YzlhYWIzMWNiMDYwMzM1NGE1MDk2MjY0ZGQ4Mzc1ZmEzNjMzMGRmNzY4NzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.a2_3SXdIfXUGKCATBz8DUVQldeAu0HAZ7o_KxdnHBjA">
> From the paper the probability of a false alarm (P_FA) is negligible, but probability of detection (P_D) should be large: <img alt="image" width="406" src="https://private-user-images.githubusercontent.com/14855676/291950720-74c52b98-b52d-4e27-898c-fcbfc73c668b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMxMTUyODcsIm5iZiI6MTcwMzExNDk4NywicGF0aCI6Ii8xNDg1NTY3Ni8yOTE5NTA3MjAtNzRjNTJiOTgtYjUyZC00ZTI3LTg5OGMtZmNiZmM3M2M2NjhiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIwVDIzMjk0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFmYmQwZGU0ODY2MWI0OWI3NWZjZTkwYzFmYjgwY2UyYjVkODIwYjIzYTg3M2ViZThmZjZhYTNjZjI3NTQ0YzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vVn6V6KucBqYhHPzo0YEbyhE9Mq4GHsZe4QSkCuc6KY">
> 
> I can test with a larger value such as 0.9 in their performance evaluation. Thank you for identifying this issue!

Thanks

**Comment by SiddharthDey** [comment]
Thanks
