### ISSUE TITLE
self.__n_miss counter starting with nmiss instead of 0

### ISSUE THREAD

**Issue by SiddharthDey** [jperdomo23/openmht#21]
The number of misses for a track is counted with the self.__nmiss attribute, but its initial value is defined as nmiss which is the maximum number of consecutive misses allowed for a track before it is deleted. But the nmiss is not used to check the max misses and the condition is hard-coded to 3 instead of using nmiss (line 38 of [kalman_filter.py](https://github.com/jonperdomo/openmht/blob/main/openmht/kalman_filter.py)):

```
if self.__nmiss > 3:
   return False
```
If we do this, then when we create a new Kalman track at frame k-1 and then assume a missed detection at frame k, self.__nmiss becomes 4 instead of 1 and hence, the branch gets pruned.

I think we should maintain two separate attributes, self.__nmiss and self.__nmiss_max, and initialize them to 0 and nmiss respectively and modify the condition to:
```
if self.__nmiss > self.__nmiss_max:
   return False
```

**Comment by jonperdomo** [comment]
Closed by PR #23 thank you!
