### ISSUE TITLE
bug of weighted graph

### ISSUE THREAD

**Issue by zl930216** [jperdomo23/openmht#3]
in WeightedGraph.mwis, max_weight is initialized min(self.__weights.values()), that would cause problem when all branches have the same score or there is only one branch. In that situation, no branch will be picked as solution. Setting it min(self.__weights.values())-1 or any value smaller than that will solve it.

**Comment by jonperdomo** [comment]
@zl930216 You must be referring to the following:
https://github.com/jonperdomo/openmht/blob/2b87b5932ba0c990cbd794e99eefe7c5fd9c14d7/weighted_graph.py#L23-L32

This loop determines the maximum weighted independent set from all nodes in the graph, which will represent the non-conflicting set of branches with the highest likelihoods / weights. I am using the minimum node weight `min(self.__weights.values())` as my initial maximum set weight. There are many cases where the sum weight of the set will be less than the lowest node weight, considering that weights can be negative. Thank you, and I will push an update correcting this.
