### ISSUE TITLE
the MWIS part will take a really long time when the number of branches reaches 35 or more.

### ISSUE THREAD

**Issue by HuMengjing** [jperdomo23/openmht#4]
I run this code with only 5 detections a frame and the N-scan number is 3,  and it takes a really long time at frame 3, in which it keeps running the bron_kerbosch() function.
I am not sure if there is a better way for this part or is that because I am not running this codes properly?
And how many detections could the algorithm handle at most when you test?
Really appreciate for your reply.

**Comment by jonperdomo** [comment]
Can you please try lowering the gating area parameter in [params.txt](https://github.com/jonperdomo/openmht/blob/bcc969e119949050a3cb84fc404138a5e3b1b17c/params.txt#L2)?

**Comment by jonperdomo** [comment]
I will test that and get back to you.

**Comment by HuMengjing** [comment]
Yeah, actually I set the gating area to 6, and my input is ground thruth(no false alarm), which means there is only one measurement can be included in the gating area.  
I'm thinking maybe there is too many vertices and edges for the MWIS( when the number of tracks reach 70, it feels like to loop forever in the bron_kerbosch() function), so I am wondering how many detections a frame could it handle and what is the N-scan window size you set? Thanks a lot :>

**Comment by jonperdomo** [comment]
Yes, I think I will try the [NetworkX maximum-weighted matching](https://networkx.github.io/documentation/networkx-1.9/reference/generated/networkx.algorithms.matching.max_weight_matching.html) implementation to see if there is an improvement in performance. For track pruning, I set an N-scan window of 1. I will also add a user-defined parameter for this, but you can modify it here in the code:
https://github.com/jonperdomo/openmht/blob/bcc969e119949050a3cb84fc404138a5e3b1b17c/openmht.py#L50

**Comment by MarwanMansour** [comment]
Any updates on this? I run into the same problem. The MWIS part is taking very long in the second frame with 14 detections.

**Comment by asafroth91** [comment]
Any update on this?  Its super slow

**Comment by jonperdomo** [comment]
I have added two missing pruning parameters from the paper: Bth for setting the maximum number of branches, and Nmiss for the maximum number of consecutive frames with missing observations for a track in commit 5627c53. Please try adjusting these parameters to improve performance.

**Comment by HuMengjing** [comment]
您发给我的信件已经收到。                             胡梦景This is an automatic reply, confirming that your e-mail was received.Thank you
