### ISSUE TITLE
Can I know the meaning of u and v in the input file?

### ISSUE THREAD

**Issue by minho8849** [jperdomo23/openmht#5]
Hello, first thanks to your good module for tracking

Can I know the meaning of u and v in the input file?

In the MOTA challenge file, the information of each box is represented as 4 variables(left-upper box coordinate, width and height of box). However, in the example file each box is indicated as 2 variables, u and v.

Can I know the meaning of u and v in the input file?

Thanks.

**Comment by MarwanMansour** [comment]
Hello @jonperdomo, thank you for the useful module!

Can you provide information about the U and V variables? They are the coordinates of the detection in the frame, but how are they translated into a bounding box, or is that not needed for the hypothesis tree generation?

Thank you.

**Comment by jonperdomo** [comment]
Hi @MarwanMansour they are the pixel coordinates in the frame. A track is updated with the detection based on whether the Mahalanobis distance between the detection and the predicted location by the Kalman filter falls below the gating area value set in the parameter file. In addition, the image area is also set in the parameter file and is the measurement space used for the null hypothesis. Please refer to the paper for more information:

_C. Kim, F. Li, A. Ciptadi and J. M. Rehg, "Multiple Hypothesis Tracking Revisited," 2015 IEEE International Conference on Computer Vision (ICCV), Santiago, 2015, pp. 4696-4704.
doi: 10.1109/ICCV.2015.533
URL: http://ieeexplore.ieee.org/stamp/stamp.jsp?tp=&arnumber=7410890&isnumber=7410356_
