### ISSUE TITLE
Meaning of frame column in input and output files

### ISSUE THREAD

**Issue by billypeanut** [jperdomo23/openmht#6]
Hi,

Just trying to understand what is meant by the 'frame'. I assume it means successive points in time where measurements are made, but I'm curious to know why they are defined as integers, and why time is not explicitly included. From the Kalman filter scripts, it doesn't look like any time step is included in the prediction, which seems a little limiting.

Danke,
BillyPeanut

**Comment by jonperdomo** [comment]
Hi @billypeanut this is a tracking-by-detection framework for visual multi-target tracking. Yes, the first column is an integer representing the frame index in the video. Please refer to this paper which describes the algorithm, although my implementation utilizes motion scoring only (no appearance scoring):
[Kim et al., 2015](https://ieeexplore.ieee.org/stamp/stamp.jsp?tp=&arnumber=7410890&isnumber=7410356&tag=1)

**Comment by jonperdomo** [comment]
I am not sure how including a time step in the prediction would be better since the data should have a constant frame rate

**Comment by billypeanut** [comment]
I see. I was thinking of this from a slightly more general use case where the measurements might come in at irregular times. In your use case with constant frame rates then you obviously won't gain anything from including the time step. Thanks.

**Comment by jonperdomo** [comment]
No problem!
