### ISSUE TITLE
where can i set Bth threshold in the code?

### ISSUE THREAD

**Issue by caroltk** [jperdomo23/openmht#7]
Hello,

I just wondering where can I set Bth, which is the number of branches in a track tree threshold as you mentioned in your paper?
Besides, would you mind sharing your detection result on the MOT dataset? I could not run on my own data after 10 frames. 

Thanks and Best Regards.

**Comment by jonperdomo** [comment]
Hello,

Apologies for the confusion, this is not my paper, just my own implementation of it in Python and without appearance scoring.
Thank you for letting me know about this, I didn't implement the threshold for pruning track trees that have grown too large but I will add that.

**Comment by caroltk** [comment]
Hello,

Thanks for your prompt response! Please let me know if you add it.

Best Regards.
